name: Documentation Check

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '*.md'
      - '**/*.jpg'
      - '**/*.png'
      - '**/*.gif'
      - 'monitoring/**'
  
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '*.md'
  
  workflow_dispatch:

jobs:
  # ==========================================
  # Job 1: Documentation Check
  # ==========================================
  check-docs:
    name: Check Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check for broken links (optional)
        run: |
          echo "Checking documentation..."
          echo "✓ README.md exists"
          [ -f "README.md" ] && echo "✓ README.md found" || exit 1
      
      - name: Validate image references
        run: |
          echo "Checking image references..."
          if grep -q "docs/images" README.md; then
            echo "✓ Image references found in README"
            ls -la docs/images/ 2>/dev/null || echo "docs/images directory not found"
          fi
      
      - name: Check file sizes
        run: |
          echo "Checking file sizes..."
          find docs/ -type f -size +5M 2>/dev/null | while read file; do
            echo "Large file detected: $file"
          done || echo "✓ No oversized files"
      
      - name: Documentation summary
        run: |
          echo "# Documentation Update Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Files Changed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          git diff --name-only HEAD~1 HEAD | grep -E '\.(md|jpg|png|gif)$' || echo "No documentation files changed" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Documentation check completed successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Note:** This is a lightweight check. Full ML pipeline was not triggered." >> $GITHUB_STEP_SUMMARY

  # ==========================================
  # Job 2: Generate Documentation Report
  # ==========================================
  doc-report:
    name: Documentation Report
    runs-on: ubuntu-latest
    needs: check-docs
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Count documentation files
        run: |
          echo "Documentation Statistics" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Type | Count |" >> $GITHUB_STEP_SUMMARY
          echo "|------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Markdown files | $(find . -name '*.md' | wc -l) |" >> $GITHUB_STEP_SUMMARY
          echo "| Images | $(find docs/ -type f \( -name '*.jpg' -o -name '*.png' -o -name '*.gif' \) 2>/dev/null | wc -l) |" >> $GITHUB_STEP_SUMMARY
          echo "| Total docs size | $(du -sh docs/ 2>/dev/null | cut -f1 || echo 'N/A') |" >> $GITHUB_STEP_SUMMARY